name: Coverage

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  generate-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql
          tools: composer:v2
          coverage: pcov

      - uses: ramsey/composer-install@v3

      - name: Execute tests
        run: vendor/bin/pest

      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./build/logs/clover.xml
